[versions]
activityCompose = "1.9.0" # https://mvnrepository.com/artifact/androidx.activity/activity-compose
androidGradlePlugin = "8.4.1" # https://mvnrepository.com/artifact/com.android.application/com.android.application.gradle.plugin
cascadeCompose = "2.3.0" # https://mvnrepository.com/artifact/me.saket.cascade/cascade-compose
composeBom = "2024.05.00" # https://mvnrepository.com/artifact/androidx.compose/compose-bom
composeNavigation = "2.8.0-beta01" # https://mvnrepository.com/artifact/androidx.navigation/navigation-compose
coreKtx = "1.13.1" # https://mvnrepository.com/artifact/androidx.core/core-ktx
dataStore = "1.1.1" # https://mvnrepository.com/artifact/androidx.datastore/datastore-preferences
dfc = "1.0.8" # https://mvnrepository.com/artifact/com.lazygeniouz/dfc
kotlin = "2.0.0" # https://mvnrepository.com/artifact/org.jetbrains.kotlin.android/org.jetbrains.kotlin.android.gradle.plugin
kotlinterGradle = "4.3.0" # // https://github.com/jeremymailen/kotlinter-gradle
kotlinxSerializationJson = "1.6.3" # https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-serialization-json
leakcanaryAndroid = "2.14" # https://mvnrepository.com/artifact/com.squareup.leakcanary/leakcanary-android
lifecycleRuntimeCompose = "2.8.0" # https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-runtime-compose
lifecycleRuntimeKtx = "2.8.0" # https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-runtime-ktx
lifecycleViewModelCompose = "2.8.0" # https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-viewmodel-compose
materialKolor = "1.6.0" # https://mvnrepository.com/artifact/com.materialkolor/material-kolor
media = "1.7.0" # https://mvnrepository.com/artifact/androidx.media/media
moshiKotlin = "1.15.1" # https://mvnrepository.com/artifact/com.squareup.moshi/moshi-kotlin
okhttp = "5.0.0-alpha.14" # https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
reorderable = "2.1.1" # https://mvnrepository.com/artifact/sh.calvin.reorderable/reorderable
retrofit = "2.11.0" # https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit
settings = "2.4.0" # https://github.com/alorma/Compose-Settings/releases
timber = "5.0.1" # https://mvnrepository.com/artifact/com.jakewharton.timber/timber
xmlUtil = "0.86.3" # https://mvnrepository.com/artifact/io.github.pdvrieze.xmlutil/core-android

[libraries]
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-animation-animation = { module = "androidx.compose.animation:animation", version = "1.7.0-beta01" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version = "1.7.0-beta01" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-settings-ui = { module = "com.github.alorma.compose-settings:ui-tiles", version.ref = "settings" }
compose-settings-ui-extended = { module = "com.github.alorma.compose-settings:ui-tiles-extended", version.ref = "settings" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }

cascade-compose = { module = "me.saket.cascade:cascade-compose", version.ref = "cascadeCompose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
dfc = { module = "com.lazygeniouz:dfc", version.ref = "dfc" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
media = { module = "androidx.media:media", version.ref = "media" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
xmlutil-android-core = { module = "io.github.pdvrieze.xmlutil:core-android", version.ref = "xmlUtil" }
xmlutil-android-serialization = { module = "io.github.pdvrieze.xmlutil:serialization-android", version.ref = "xmlUtil" }

[bundles]
compose = [
    "compose-activity",
    "compose-animation-animation",
    "compose-animation-graphics",
    "compose-foundation",
    "compose-material-icons-core",
    "compose-material-icons-extended",
    "compose-material3",
    "compose-runtime-livedata",
    "compose-settings-ui",
    "compose-settings-ui-extended",
    "compose-ui-tooling",
    "compose-ui-ui",
    "compose-navigation"
]
compose-utils = [
    "cascade-compose",
    "lifecycle-runtime-compose",
    "materialKolor",
]
xmlUtils = [
    "xmlutil-android-core",
    "xmlutil-android-serialization"
]
retrofit = [
    "retrofit",
    "retrofit-serialization"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gradle-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinterGradle" }
kotlin-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
