[versions]
accompanistPermissions = "0.35.0-alpha" # https://mvnrepository.com/artifact/com.google.accompanist/accompanist-permissions
activityCompose = "1.8.2" # https://mvnrepository.com/artifact/androidx.activity/activity-compose
androidGradlePlugin = "8.3.0-rc02" # https://mvnrepository.com/artifact/com.android.application/com.android.application.gradle.plugin
androidKotlin = "1.9.22" # https://mvnrepository.com/artifact/org.jetbrains.kotlin.android/org.jetbrains.kotlin.android.gradle.plugin
cascadeCompose = "2.3.0" # https://mvnrepository.com/artifact/me.saket.cascade/cascade-compose
composeBom = "2024.02.01" # https://mvnrepository.com/artifact/androidx.compose/compose-bom
coreKtx = "1.12.0" # https://mvnrepository.com/artifact/androidx.core/core-ktx
dfc = "1.0.8" # https://mvnrepository.com/artifact/com.lazygeniouz/dfc
kotlinCompiler = "1.5.9" # https://developer.android.com/jetpack/androidx/releases/compose-compiler
kotlinterGradle = "4.2.0" # // https://github.com/jeremymailen/kotlinter-gradle
kotlinxSerializationJson = "1.6.3" # https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-serialization-json
leakcanaryAndroid = "2.13" # https://mvnrepository.com/artifact/com.squareup.leakcanary/leakcanary-android
lifecycleRuntimeCompose = "2.7.0" # https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-runtime-compose
lifecycleRuntimeKtx = "2.7.0" # https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-runtime-ktx
lifecycleViewModelCompose = "2.7.0" # https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-viewmodel-compose
media = "1.7.0" # https://mvnrepository.com/artifact/androidx.media/media
moshiKotlin = "1.15.1" # https://mvnrepository.com/artifact/com.squareup.moshi/moshi-kotlin
okhttp = "5.0.0-alpha.12" # https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
preferenceKtx = "1.2.0" # https://mvnrepository.com/artifact/androidx.preference/preference-ktx
reorderable = "1.3.1"
retrofit = "2.9.0" # https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit
retrofit2KotlinxSerializationConverter = "1.0.0" # https://mvnrepository.com/artifact/com.jakewharton.retrofit/retrofit2-kotlinx-serialization-converter
settings = "1.0.3" # https://mvnrepository.com/artifact/com.github.alorma/compose-settings-storage-preferences
timber = "5.0.1" # https://mvnrepository.com/artifact/com.jakewharton.timber/timber
xmlUtil = "0.86.3" # https://mvnrepository.com/artifact/io.github.pdvrieze.xmlutil/core-android
oboe = "1.8.1"

[libraries]
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-settings-storage-preferences = { module = "com.github.alorma:compose-settings-storage-preferences", version.ref = "settings" }
compose-settings-ui-m3 = { module = "com.github.alorma:compose-settings-ui-m3", version.ref = "settings" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
cascade-compose = { module = "me.saket.cascade:cascade-compose", version.ref = "cascadeCompose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
dfc = { module = "com.lazygeniouz:dfc", version.ref = "dfc" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }
media = { module = "androidx.media:media", version.ref = "media" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
xmlutil-android-core = { module = "io.github.pdvrieze.xmlutil:core-android", version.ref = "xmlUtil" }
xmlutil-android-serialization = { module = "io.github.pdvrieze.xmlutil:serialization-android", version.ref = "xmlUtil" }
oboe = { module = "com.google.oboe:oboe", version.ref = "oboe" }

[bundles]
compose = [
    "compose-activity",
    "compose-animation-animation",
    "compose-animation-graphics",
    "compose-foundation",
    "compose-material-icons-core",
    "compose-material-icons-extended",
    "compose-material3",
    "compose-runtime-livedata",
    "compose-settings-storage-preferences",
    "compose-settings-ui-m3",
    "compose-ui-tooling",
    "compose-ui-ui",
]
compose-utils = [
    "cascade-compose",
    "lifecycle-runtime-compose",
    "accompanist-permissions",
]
xmlUtils = [
    "xmlutil-android-core",
    "xmlutil-android-serialization"
]
retrofit = [
    "retrofit",
    "retrofit2-kotlinx-serialization-converter"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "androidKotlin" }
gradle-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinterGradle" }
